name: Parsers test

type:
    workflow_dispatch:
    pull_request:
        paths:
            - 'src/id/mgkomik/src/eu/kanade/tachiyomi/extension/id/**'

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: 'gradle'
            -   run: ./gradlew assemble